[package]
name = "killerwhale"
version = "0.1.0"
edition = "2024"

# bevy Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# bevy Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# bevy dyamic linking
[dependencies]
bevy = { version = "0.19.0", features = ["dynamic_linking"] }

