[package]
name = "killerwhale"
version = "0.1.0"
edition = "2024"

# bevy Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# bevy Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3


[dependencies]
bevy = { version = "0.19.0", features = ["bevy_dev_tools"] }
bevy_rapier3d = { version = "0.35.0", features = [ "simd-stable", "debug-render-3d" ] }
bevy_egui = "0.41.1"

